"""Deghoster V2 — FULL-EVENT fine-tune of the crop-trained PTv3-decoder model.

Targets the crop->full-event domain gap identified in the v1 study: v1
(trained on nearest-10240-point crops) improved full-event photon charge
completeness 0.653 -> 0.686 but remains 0.13 below the 0.815 hasmatch
ceiling, while being TIED with LoRA at crop-level mIoU — i.e., crop metrics
saturate and the remaining loss plausibly lives in the deployment domain
(100-300k-point events vs 10k-point training crops).

Deltas vs deghost-ptv3decoder-v1-frozenenc-extbnb.py:
  - WARM START from the v1 model_best (crop-trained, ep19): `weight` points
    at it; CheckpointLoader loads model weights (SonataFinetuneCheckpoint-
    Loader no-ops — a training ckpt has no teacher.* keys).
  - FULL EVENTS: BiasedSphereCrop point_max 10240 -> 300_000. The crop
    then engages only on pathological events (nearest-k memory guard);
    everything else passes through whole. Same augmentation chain.
  - batch 96 crops -> 4 events (2/GPU on 2xA100): ~2x180k pts/GPU ~ 20 GB
    activations under xformers, margin for 300k monsters.
  - SUBSET LISTS (created by the submit script): 80k train / 2000 val
    events. Full-event compute is ~15-18x per event vs a crop; 2 epochs
    over 80k events = 40k steps ≈ 13-22 h. Low-LR fine-tune doesn't need
    the full 410k list.
  - lr 5e-4 -> 1e-4 OneCycle (fine-tune), epoch=eval_epoch=2.

Decision metric unchanged: swap into the cascade config, rerun valtest +
particle_slice_completeness — does post-deghost completeness move from
0.686 toward 0.815?
"""

_base_ = ["./deghost-ptv3decoder-v1-frozenenc-extbnb.py"]

# Warm start from the crop-trained v1 (see docstring).
weight = (
    "/cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/"
    "exp/deghost_ptv3decoder_v1_frozenenc_extbnb/model/model_best.pth"
)

save_path      = "exp/deghost_ptv3decoder_v2_fullevent_ft"
epoch          = 2
eval_epoch     = 2
base_lr        = 1e-4
batch_size     = 4          # 2 events/GPU on 2x A100-80GB
batch_size_val = 4
num_worker     = 8          # full events are heavy per worker
num_worker_val = 4

optimizer = dict(type="AdamW", lr=base_lr, weight_decay=0.01)
scheduler = dict(
    type="OneCycleLR",
    max_lr=[base_lr, 0.0, 0.0],
    pct_start=0.1,
    anneal_strategy="cos",
    div_factor=10.0,
    final_div_factor=100.0,
)

# Subset lists — generated by submit_deghost_fullevent_ft_a100.sh from the
# LANTERN lists. Deliberately non-existent until the script makes them.
_FT_LIST_DIR = ("/cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/"
                "kpv2_pointcept/exp/deghost_ptv3decoder_v2_fullevent_ft")
TRAIN_FILE_LIST = f"{_FT_LIST_DIR}/ft_train_80k.txt"
VAL_FILE_LIST   = f"{_FT_LIST_DIR}/ft_val_2k.txt"

# Transform lists merge WHOLESALE (no per-item merge), so both are restated
# in full; the only changes vs v1 are point_max 10240 -> 300_000 and the
# subset data_list_file paths.
grid_size    = 0.25
coord_scale  = 1036.0 * 3**0.5 / 2.0 / 5.0
_scaled_grid_size = 0.0013932197615579773
_jitter_sigma     = 0.0003483049403894943
_strength_jitter_sigma = 0.05
_strength_jitter_clip  = 0.05
max_points_fullevent = 300_000
min_points_spherecrop = 4096
biased_spherecrop_radius = 20.0

data = dict(
    num_classes=2,
    ignore_index=-1,
    names=["real", "ghost"],
    train=dict(
        type="LArTPCDataset",
        data_list_file=TRAIN_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=True,
        true_points_only=False,
        exclude_other=True,
        drop_cosmics=False,
        drop_cosmics_prob=0.0,
        transform=[
            dict(
                type="BiasedSphereCrop",
                anchor_points_key="nu_vertices",
                anchor_pdf_key=None,
                radius=biased_spherecrop_radius,
                point_max=max_points_fullevent,   # v2: full events; crop
                point_min=min_points_spherecrop,  # only guards monsters
                prob_random=0.5,
                max_retries=100,
                fallback_to_random=True,
            ),
            dict(type="GridSample", grid_size=grid_size, hash_type="fnv",
                 mode="train", return_grid_coord=True),
            dict(type="NormalizeCoord", center=[125.0, 0.0, 518.0],
                 scale=coord_scale),
            dict(type="LogTransform", min_val=0.01, max_val=1000.0,
                 log=True, keys=("strength",)),
            dict(type="MultiplicativeRandomJitter",
                 sigma=_strength_jitter_sigma, clip=_strength_jitter_clip,
                 keys="strength", p=0.8, log_space=True),
            dict(type="HasmatchAsGhost", real_target_index=0,
                 ghost_target_index=1, ignore_index=-1),
            dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
            dict(type="RandomRotate", angle=[-1, 1], axis="z",
                 center=[0, 0, 0], p=0.8),
            dict(type="RandomRotate", angle=[-1, 1], axis="x",
                 center=[0, 0, 0], p=0.8),
            dict(type="RandomRotate", angle=[-1, 1], axis="y",
                 center=[0, 0, 0], p=0.8),
            dict(type="RandomFlip", p=0.5, axes=("x", "y", "z")),
            dict(type="RandomJitter", sigma=_jitter_sigma,
                 clip=_scaled_grid_size, keys=("coord",)),
            dict(type="ToTensor"),
            dict(type="Collect",
                 keys=("coord", "grid_coord", "segment"),
                 feat_keys=("coord", "strength")),
        ],
        test_mode=False,
    ),
    val=dict(
        type="LArTPCDataset",
        split="val",
        data_list_file=VAL_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=True,
        true_points_only=False,
        exclude_other=True,
        drop_cosmics=False,
        drop_cosmics_prob=0.0,
        transform=[
            dict(
                type="BiasedSphereCrop",
                anchor_points_key="nu_vertices",
                anchor_pdf_key=None,
                radius=biased_spherecrop_radius,
                point_max=max_points_fullevent,
                point_min=min_points_spherecrop,
                prob_random=1.0,
                max_retries=100,
                fallback_to_random=True,
            ),
            dict(type="GridSample", grid_size=grid_size, hash_type="fnv",
                 mode="train", return_grid_coord=True),
            dict(type="NormalizeCoord", center=[125.0, 0.0, 518.0],
                 scale=coord_scale),
            dict(type="LogTransform", min_val=0.01, max_val=1000.0,
                 log=True, keys=("strength",)),
            dict(type="HasmatchAsGhost", real_target_index=0,
                 ghost_target_index=1, ignore_index=-1),
            dict(type="ToTensor"),
            dict(type="Collect",
                 keys=("coord", "grid_coord", "segment"),
                 feat_keys=("coord", "strength")),
        ],
        test_mode=False,
    ),
    test=dict(),
)
