# run-1 intrinsic-nue overlay HALF: filenos 1-2014 of the RESERVED list, MC mode + truth sidecars,
# 9 serial batches of 250 (~41 events/file, ~5.9 MB/event -> ~485 GB). Crashers handled by retry_incomplete_tranche.sh.
mcc9_v28_run1_nueintrinsics /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_nueintrinsics_RESERVED.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_nueintrinsics_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/markers 1 250
mcc9_v28_run1_nueintrinsics /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_nueintrinsics_RESERVED.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_nueintrinsics_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/markers 251 500
mcc9_v28_run1_nueintrinsics /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_nueintrinsics_RESERVED.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_nueintrinsics_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/markers 501 750
mcc9_v28_run1_nueintrinsics /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_nueintrinsics_RESERVED.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_nueintrinsics_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/markers 751 1000
mcc9_v28_run1_nueintrinsics /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_nueintrinsics_RESERVED.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_nueintrinsics_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/markers 1001 1250
mcc9_v28_run1_nueintrinsics /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_nueintrinsics_RESERVED.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_nueintrinsics_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/markers 1251 1500
mcc9_v28_run1_nueintrinsics /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_nueintrinsics_RESERVED.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_nueintrinsics_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/markers 1501 1750
mcc9_v28_run1_nueintrinsics /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_nueintrinsics_RESERVED.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_nueintrinsics_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/markers 1751 2000
mcc9_v28_run1_nueintrinsics /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_nueintrinsics_RESERVED.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_nueintrinsics_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_nueintrinsics_half/markers 2001 2014
