# run-1 BNB nu overlay HALF sample: filenos 1-4740 of the TRAINPOOL list, MC mode + truth sidecars,
# 19 serial batches of 250 (~194 GB / 1000 filenos -> ~920 GB). Known duds (26 filenos <= 160) fail without markers; do not blind-retry.
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 1 250
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 251 500
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 501 750
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 751 1000
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 1001 1250
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 1251 1500
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 1501 1750
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 1751 2000
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 2001 2250
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 2251 2500
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 2501 2750
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 2751 3000
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 3001 3250
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 3251 3500
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 3501 3750
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 3751 4000
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 4001 4250
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 4251 4500
mcc9_v28_run1_bnboverlay /cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/kpv2_pointcept/lartpc/data_prep/uboone_official/training_data_ledger/mcc9_v28_run1_bnboverlay_TRAINPOOL.txt /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/merged_sp mc /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/truth_sidecar /cluster/tufts/wongjiradlab/larbys/data/mcc9_scratch/tier2_staging/run1_bnboverlay_half /cluster/tufts/wongjiradlab/larbys/data/larformer/run1_bnboverlay_half/markers 4501 4740
