#!/usr/bin/env python3
"""
Generate the Phase 0.5 config family into configs/lartpc/p05/.

See lartpc/pretraining_studies/phase0_phase05_implementation_plan.md (WP5).

All pretraining configs derive from pretrain-sonata-v8-extbnb-mc-combined-larmatch.py
with the Phase 0.5 deltas applied:
  - MC-only ghost-dropped data (data_only=False, true_points_only=True,
    filter_larmatch=False, lists from lartpc/filelists/)
  - locked budget: batch 48, peak LR 2e-4, 12 epochs (~5.0M images)
  - weights-only snapshot schedule for probe curves vs images seen
  - truth labels carried into views (view_keys += segment) + M5
    BatchCompositionLogger

Supervised-ceiling configs (P05A) train the SAME architecture end-to-end
(SonataSegmentor with freeze_backbone=False, up_cast_level=4) on the SAME data
distribution as the probe protocol (nu-anchored crops, drop_cosmics=0.9), so
the M6 fraction-of-ceiling comparison is apples-to-apples.

Rerun after editing; generated files carry a DO-NOT-HAND-EDIT banner.
"""
import os

OUT_DIR = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "configs", "lartpc", "p05"
))

FILELIST_DIR = "/projects/u6jo/work/pointcept/lartpc/filelists"
MC_TRAIN = f"{FILELIST_DIR}/h5list_v3_mc_only_train.txt"
MC_VAL = f"{FILELIST_DIR}/h5list_v3_mc_only_val.txt"
N_MC_TRAIN_FILES = 415_680

# Locked budget (implementation plan §1.4 / §4)
BATCH_SIZE = 48
BASE_LR = 2.0e-4
EPOCH = 12  # 12 x 415,680 = 4,988,160 images ~= 5M

# Snapshot schedule in IMAGES SEEN (converted to iters per config batch size):
# log-doubling from 24k to 768k, then every 768k.
SNAPSHOT_IMG_ANCHORS = (
    [24_000 * 2 ** i for i in range(6)]           # 24k .. 768k
    + [768_000 * i for i in range(2, 7)]          # 1.536M .. 4.608M
)


def snapshot_iters(batch_size):
    return [img // batch_size for img in SNAPSHOT_IMG_ANCHORS]


BANNER = '''"""
AUTO-GENERATED by lartpc/pretraining_studies/gen_p05_configs.py — DO NOT HAND-EDIT.
Regenerate with:  python3 lartpc/pretraining_studies/gen_p05_configs.py

@HEADER@
"""
'''

FREEROT_AUG = '''            dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
            # Free 3-axis rotations + swap-less x/y/z flips: replicates the
            # v6/v7/v8 policy exactly (charge-INconsistent by design).
            dict(type="RandomRotate", angle=[-1, 1], axis="z", center=[0, 0, 0], p=0.8),
            dict(type="RandomRotate", angle=[-1, 1], axis="x", center=[0, 0, 0], p=0.8),
            dict(type="RandomRotate", angle=[-1, 1], axis="y", center=[0, 0, 0], p=0.8),
            dict(type="RandomFlip", p=0.5, axes=("x", "y", "z")),
            dict(
                type="RandomJitter",
                sigma=scaled_grid_size / 4,
                clip=scaled_grid_size,
                keys=("coord",),
            ),'''

DETSYM_AUG = '''            dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
            # Detector symmetries only: y-flip and z-flip with u<->v
            # charge-column swap (reviewed correct — implementation plan §1.5).
            # No rotations (tomographic charge consistency), no x-flip
            # (drift-direction asymmetry: diffusion, attenuation).
            dict(type="RandomFlipAxis", p=0.5, axis="y", center="mean",
                 coord_scale=1.0, swap_strength_columns=@SWAP@,
                 wire_projections=None),
            dict(type="RandomFlipAxis", p=0.5, axis="z", center="mean",
                 coord_scale=1.0, swap_strength_columns=@SWAP@,
                 wire_projections=None),
            dict(
                type="RandomJitter",
                sigma=scaled_grid_size / 4,
                clip=scaled_grid_size,
                keys=("coord",),
            ),'''

CHANNEL_REDUCE_LINE = '''    # P05B.4: reduce the 3 per-plane pixvals to one plane-summed scalar
    # (invariant under the u/v swap) BEFORE the log transform.
    dict(type="ChannelReduce", key="strength", mode="sum"),
'''

# =============================================================================
# SSL pretraining template
# =============================================================================
SSL_TEMPLATE = BANNER + '''
_base_ = ["../../_base_/default_runtime.py"]

# ---- Phase 0.5 locked budget (do not vary within P05 comparisons) ----
seed = 0
batch_size = @BATCH_SIZE@
batch_size_val = 8
num_worker = 24
mix_prob = 0
clip_grad = 1.0
empty_cache = True
enable_amp = False
evaluate = False  # SSL runs are probed offline at Tufts (implementation plan WP3)
find_unused_parameters = False

skip_dataloader_on_resume = True
resume_seed_strategy = "per_resume"

flash_backend = "flash_attn"
amp_dtype = "bfloat16"

enable_wandb = True
wandb_project = "pointcept_p05_pretrain"
save_path = "sonata/p05/@RUN_ID@"

TRAIN_FILE_LIST = "@TRAIN_LIST@"
VAL_FILE_LIST = "@VAL_LIST@"

max_points_per_view = @POINT_MAX@
max_points_spherecrop = @POINT_MAX@
min_points_spherecrop = @MIN_POINTS@
biased_spherecrop_radius = 20.0

# scheduler settings
epoch = @EPOCH@
eval_epoch = @EPOCH@
base_lr = @BASE_LR@
lr_final_div_factor = 1000.0
lr_pct_start = 0.06
lr_decay = 0.9  # layer-wise lr decay
base_wd = 0.04
final_wd = 0.2

# LArTPC scale parameters
grid_size = 0.25  # cm
wire_scale = 1.0 / 3456.0
coord_scale = 1036.0 * 3**0.5 / 2.0 / 5.0
scaled_grid_size = grid_size / coord_scale

# Weights-only snapshots for probe curves (metric vs images seen); the
# snapshot/ directory is rsync'd to Tufts as points accumulate (WP2/WP3).
snapshot_at_iters = @SNAPSHOT_ITERS@

# model settings
model = dict(
    type="Sonata-v1m1",
    backbone=dict(
        type="PT-v3m2",  # Must use v3m2 for SONATA (supports mask_token)
        in_channels=@IN_CHANNELS@,
        order=("z", "z-trans", "hilbert", "hilbert-trans"),
        stride=(2, 2, 2, 2),
        enc_depths=(3, 3, 3, 9, 3),
        enc_channels=(48, 96, 192, 384, 512),
        enc_num_head=(3, 6, 12, 24, 32),
        enc_patch_size=(256, 256, 256, 256, 256),
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        attn_drop=0.0,
        proj_drop=0.0,
        drop_path=0.3,
        shuffle_orders=True,
        pre_norm=True,
        enable_rpe=False,
        enable_flash=True,
        flash_backend=flash_backend,
        upcast_attention=False,
        upcast_softmax=False,
        traceable=True,
        enc_mode=True,
        mask_token=True,
    ),
    teacher_custom=dict(
        attn_drop=0.0,
        proj_drop=0.0,
        drop_path=0.0,
    ),
    head_in_channels=1088,  # up_cast_level=2: 192 + 384 + 512
    head_hidden_channels=2048,
    head_embed_channels=256,
    head_num_prototypes=@PROTOTYPES@,
    num_global_view=2,
    num_local_view=6,
    mask_size_start=2.0 / coord_scale,
    mask_size_base=15.0 / coord_scale,
    mask_size_warmup_ratio=0.06,
    mask_ratio_start=0.2,
    mask_ratio_base=0.7,
    mask_ratio_warmup_ratio=0.06,
    mask_jitter=0.125 / coord_scale,
    teacher_temp_start=0.04,
    teacher_temp_base=0.07,
    teacher_temp_warmup_ratio=0.06,
    student_temp=0.1,
    mask_loss_weight=2 / 8,
    roll_mask_loss_weight=2 / 8,
    unmask_loss_weight=4 / 8,
    momentum_base=0.994,
    momentum_final=1.0,
    match_max_k=8,
    match_max_r=16.0 * grid_size / coord_scale,
    up_cast_level=2,
)

# Layer-wise learning rate decay
enc_depths = model["backbone"]["enc_depths"]
param_dicts = [
    dict(
        keyword=f"enc{e}.block{b}.",
        lr=base_lr * lr_decay ** (sum(enc_depths) - sum(enc_depths[:e]) - b - 1),
    )
    for e in range(len(enc_depths))
    for b in range(enc_depths[e])
]
del enc_depths

optimizer = dict(type="AdamW", lr=base_lr, weight_decay=base_wd)
scheduler = dict(
    type="OneCycleLR",
    max_lr=[base_lr] + [g["lr"] for g in param_dicts],
    pct_start=lr_pct_start,
    anneal_strategy="cos",
    div_factor=100.0,
    final_div_factor=lr_final_div_factor,
)

# dataset settings
dataset_type = "LArTPCDataset"
data_root = "data/lartpc"

transform = [
    dict(
        type="GridSample",
        grid_size=grid_size,
        hash_type="fnv",
        mode="train",
        return_grid_coord=True,
    ),
    dict(type="BiasedSphereCrop",
        anchor_points_key=@CROP_ANCHOR_KEY@,
        anchor_pdf_key=None,
        radius=biased_spherecrop_radius,
        point_max=max_points_spherecrop,
        point_min=min_points_spherecrop,
        prob_random=@CROP_PROB_RANDOM@,
        max_retries=100,
        fallback_to_random=True),
    dict(type="NormalizeCoord", center=[125.0, 0.0, 1036.0 / 2.0], scale=coord_scale),
@STRENGTH_REDUCE@    dict(
        type="LogTransform",
        min_val=0.01,
        max_val=1000.0,
        log=True,
        keys=("strength",),
    ),
    dict(type="Copy", keys_dict={"coord": "origin_coord"}),
    dict(
        type="MultiViewGenerator",
        # "segment" rides along so the M5 BatchCompositionLogger can measure
        # per-batch truth-class fractions (labels are NOT used by the loss).
        view_keys=("coord", "origin_coord", "strength", "segment"),
        global_view_num=2,
        global_view_scale=(0.4, 1.0),
        local_view_num=6,
        local_view_scale=(0.1, 0.4),
        global_shared_transform=[
            dict(
                type="MultiplicativeRandomJitter",
                sigma=0.05,
                clip=0.05,
                keys=("strength"),
                p=0.8,
                log_space=True,
            ),
        ],
        global_transform=[
@GLOBAL_AUG@
        ],
        local_transform=[
@LOCAL_AUG@
        ],
        max_size=max_points_per_view,
    ),
    dict(type="ToTensor"),
    dict(type="Update", keys_dict={"grid_size": scaled_grid_size}),
    dict(
        type="Collect",
        keys=(
            "global_origin_coord",
            "global_coord",
            "global_offset",
            "global_segment",
            "local_origin_coord",
            "local_coord",
            "local_offset",
            "grid_size",
            "name",
        ),
        offset_keys_dict=dict(),
        global_feat_keys=("global_coord", "global_strength",),
        local_feat_keys=("local_coord", "local_strength",),
    ),
]

# Single-view validation pipeline (kept consistent with the feature pipeline;
# only used if an in-loop evaluator is enabled).
val_transform = [
    dict(
        type="GridSample",
        grid_size=grid_size,
        hash_type="fnv",
        mode="train",
        return_grid_coord=True,
    ),
    dict(type="BiasedSphereCrop",
        anchor_points_key=None,
        anchor_pdf_key=None,
        radius=biased_spherecrop_radius,
        point_max=max_points_spherecrop,
        point_min=min_points_spherecrop,
        prob_random=1.0,
        max_retries=100,
        fallback_to_random=True),
    dict(type="NormalizeCoord", center=[125.0, 0.0, 1036.0 / 2.0], scale=coord_scale),
@STRENGTH_REDUCE@    dict(
        type="LogTransform",
        min_val=0.01,
        max_val=1000.0,
        log=True,
        keys=("strength",),
    ),
    dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
    dict(type="ToTensor"),
    dict(
        type="Collect",
        keys=("coord", "grid_coord", "segment"),
        feat_keys=("coord", "strength"),
    ),
]

ssnet_class_names = [
    "electron", "muon", "pion", "proton", "gamma", "michel", "delta", "led",
]

data = dict(
    num_classes=8,
    ignore_index=-1,
    names=ssnet_class_names,
    train=dict(
        type=dataset_type,
        split="train",
        data_list_file=TRAIN_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=False,
        exclude_other=False,
        transform=transform,
        test_mode=False,
        loop=1,
        # ---- Phase 0.5: ghost-dropped MC with truth loaded ----
        true_points_only=True,
        data_only=False,
        filter_larmatch=False,
        drop_cosmics=@DROP_COSMICS@,
        drop_cosmics_prob=@DROP_COSMICS_PROB@,
    ),
    val=dict(
        type=dataset_type,
        split="val",
        data_list_file=VAL_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=False,
        exclude_other=False,
        transform=val_transform,
        test_mode=False,
        loop=1,
        true_points_only=True,
        data_only=False,
        filter_larmatch=False,
    ),
)

hooks = [
    dict(type="CheckpointLoader", extend_scheduler=False),
    dict(type="ModelHook"),
    dict(type="WeightDecaySchedular", base_value=base_wd, final_value=final_wd,
         extend_scheduler=False, original_total_steps=None),
    dict(type="IterationTimer", warmup_iter=2),
    dict(type="InformationWriter"),
    dict(type="CheckpointSaver", save_freq=1),
    # Resumable mid-epoch saves + retained weights-only snapshots (WP2).
    dict(type="IterCheckpointSaver", save_iter_freq=50, keep_history=False,
         snapshot_at_iters=snapshot_at_iters),
    dict(type="SignalCheckpointHook", check_every_n_iter=30),
    # M5: per-batch truth-class composition (implementation plan WP5).
    dict(type="BatchCompositionLogger", log_frequency=50,
         segment_key="global_segment"),
    dict(
        type="GradScalerMonitor",
        log_frequency=10,
        prefix="grad_scaler",
        warn_on_overflow=True,
        warn_on_low_scale=1.0,
    ),
    dict(
        type="AdamStateMonitor",
        log_frequency=100,
        prefix="adam_state",
        track_layers=True,
        track_histograms=False,
        histogram_frequency=500,
    ),
    dict(
        type="PrototypeUsageLogger",
        log_frequency=10,
        prefix="prototypes",
    ),
    dict(
        type="FeatureStdMonitor",
        log_frequency=10,
        prefix="feature_std",
        monitor_student=True,
        monitor_teacher=True,
        track_channels=False,
    ),
]
'''

# =============================================================================
# Supervised ceiling template (P05A)
# =============================================================================
SUPERVISED_TEMPLATE = BANNER + '''
_base_ = ["../../_base_/default_runtime.py"]

seed = 0
batch_size = @BATCH_SIZE@
batch_size_val = 48
num_worker = 24
mix_prob = 0.0
clip_grad = 1.0
empty_cache = False
enable_amp = False
evaluate = True
# The wrapped Sonata module's student branch is unused when training the
# (teacher) encoder end-to-end through SonataSegmentor.
find_unused_parameters = True

skip_dataloader_on_resume = True
resume_seed_strategy = "per_resume"

flash_backend = "flash_attn"
amp_dtype = "bfloat16"

enable_wandb = True
wandb_project = "pointcept_semseg"
save_path = "sonata/p05/@RUN_ID@"

TRAIN_FILE_LIST = "@TRAIN_LIST@"
VAL_FILE_LIST = "@VAL_LIST@"

grid_size = 0.25
wire_scale = 1.0 / 3456.0
coord_scale = 1036.0 * 3**0.5 / 2.0 / 5.0
scaled_grid_size = grid_size / coord_scale

max_points_spherecrop = 20480
min_points_spherecrop = 4096
biased_spherecrop_radius = 20.0

epoch = @EPOCH@
eval_epoch = @EPOCH@
base_lr = @BASE_LR@

# =============================================================================
# Supervised ceiling: SAME architecture and feature path as the SSL probes
# (SonataSegmentor + PT-v3m2 encoder + up_cast_level=4 + linear head), trained
# END-TO-END from random init. This makes the M6 fraction-of-ceiling
# comparison probe-vs-ceiling apples-to-apples.
# =============================================================================
model = dict(
    type="SonataSegmentor",
    num_classes=8,
    backbone_out_channels=1232,  # 48+96+192+384+512 at up_cast_level=4
    backbone=dict(
        type="Sonata-v1m1",
        backbone=dict(
            type="PT-v3m2",
            in_channels=@IN_CHANNELS@,
            order=("z", "z-trans", "hilbert", "hilbert-trans"),
            stride=(2, 2, 2, 2),
            enc_depths=(3, 3, 3, 9, 3),
            enc_channels=(48, 96, 192, 384, 512),
            enc_num_head=(3, 6, 12, 24, 32),
            enc_patch_size=(256, 256, 256, 256, 256),
            mlp_ratio=4,
            qkv_bias=True,
            qk_scale=None,
            attn_drop=0.0,
            proj_drop=0.0,
            drop_path=0.3,
            shuffle_orders=True,
            pre_norm=True,
            enable_rpe=False,
            enable_flash=True,
            flash_backend=flash_backend,
            upcast_attention=False,
            upcast_softmax=False,
            traceable=True,
            enc_mode=True,
            mask_token=True,
        ),
        head_in_channels=1088,
        head_hidden_channels=2048,
        head_embed_channels=256,
        head_num_prototypes=4096,
        num_global_view=2,
        num_local_view=6,
        up_cast_level=4,
    ),
    criteria=[
        dict(
            type="FocalLoss",
            gamma=2.0,
            alpha=0.5,
            loss_weight=1.0,
            ignore_index=-1,
            reduction="mean",
        ),
        dict(type="LovaszLoss", mode="multiclass", loss_weight=0.1, ignore_index=-1),
    ],
    freeze_backbone=False,  # supervised: train the encoder end-to-end
    class_priors=[0.052, 0.797, 0.009, 0.024, 0.030, 0.006, 0.077, 0.007],
)

optimizer = dict(type="AdamW", lr=base_lr, weight_decay=0.04)
scheduler = dict(
    type="OneCycleLR",
    max_lr=[base_lr],
    pct_start=0.06,
    anneal_strategy="cos",
    div_factor=100.0,
    final_div_factor=1000.0,
)

dataset_type = "LArTPCDataset"
data_root = "data/lartpc"

# Data distribution mirrors the probe protocol (BASE_LINPROBE): nu-anchored
# crops (prob_random=0.25) and drop_cosmics=0.9, so ceiling and probe numbers
# are measured on the same event distribution.
train_transform = [
    dict(
        type="GridSample",
        grid_size=grid_size,
        hash_type="fnv",
        mode="train",
        return_grid_coord=True,
    ),
    dict(type="BiasedSphereCrop",
        anchor_points_key="nu_vertices",
        anchor_pdf_key=None,
        radius=biased_spherecrop_radius,
        point_max=max_points_spherecrop,
        point_min=min_points_spherecrop,
        prob_random=0.25,
        max_retries=100,
        fallback_to_random=True),
    dict(type="NormalizeCoord", center=[125.0, 0.0, 1036.0 / 2.0], scale=coord_scale),
    dict(
        type="LogTransform",
        min_val=0.01,
        max_val=1000.0,
        log=True,
        keys=("strength",),
    ),
@ZERO_CHARGE@@AUG_BLOCK@
    dict(type="ToTensor"),
    dict(
        type="Collect",
        keys=("coord", "grid_coord", "segment", "segment_counts"),
        feat_keys=("coord", "strength"),
    ),
]

val_transform = [
    dict(
        type="GridSample",
        grid_size=grid_size,
        hash_type="fnv",
        mode="train",
        return_grid_coord=True,
    ),
    dict(type="BiasedSphereCrop",
        anchor_points_key="nu_vertices",
        anchor_pdf_key=None,
        radius=biased_spherecrop_radius,
        point_max=max_points_spherecrop,
        point_min=min_points_spherecrop,
        prob_random=0.25,
        max_retries=100,
        fallback_to_random=True),
    dict(type="NormalizeCoord", center=[125.0, 0.0, 1036.0 / 2.0], scale=coord_scale),
    dict(
        type="LogTransform",
        min_val=0.01,
        max_val=1000.0,
        log=True,
        keys=("strength",),
    ),
@ZERO_CHARGE@    dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
    dict(type="ToTensor"),
    dict(
        type="Collect",
        keys=("coord", "grid_coord", "segment", "segment_counts"),
        feat_keys=("coord", "strength"),
    ),
]

ssnet_class_names = [
    "electron", "muon", "pion", "proton", "gamma", "michel", "delta", "led",
]

data = dict(
    num_classes=8,
    ignore_index=-1,
    names=ssnet_class_names,
    train=dict(
        type=dataset_type,
        split="train",
        data_list_file=TRAIN_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=False,
        exclude_other=True,
        transform=train_transform,
        test_mode=False,
        loop=1,
        true_points_only=True,
        data_only=False,
        filter_larmatch=False,
        drop_cosmics=True,
        drop_cosmics_prob=0.9,
    ),
    val=dict(
        type=dataset_type,
        split="val",
        data_list_file=VAL_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=False,
        exclude_other=True,
        transform=val_transform,
        test_mode=False,
        loop=1,
        true_points_only=True,
        data_only=False,
        filter_larmatch=False,
        drop_cosmics=True,
        drop_cosmics_prob=0.9,
    ),
)

hooks = [
    dict(type="CheckpointLoader"),
    dict(type="IterationTimer", warmup_iter=2),
    dict(type="InformationWriter"),
    # In-loop val on Isambard (implementation plan §1.4): mid-epoch evals log
    # on the global-Iter axis (WP2.5 fix in SemSegEvaluator).
    dict(type="SemSegEvaluator", write_cls_iou=True, eval_freq=1000),
    dict(type="CheckpointSaver", save_freq=1),
    dict(type="IterCheckpointSaver", save_iter_freq=500, keep_history=False),
    dict(type="SignalCheckpointHook", check_every_n_iter=30),
    dict(type="BatchCompositionLogger", log_frequency=50, segment_key="segment"),
]
'''


# =============================================================================
# Tufts linear-probe template (WP3): probes P05/v8-era snapshots.
# The existing linearprobe-sonata-lartpc-v5-noghost.py CANNOT load these
# checkpoints (it assumes strength-only in_channels=3); this config matches
# the P05 feature pipeline (coord+strength, NormalizeCoord+LogTransform).
# =============================================================================
PROBE_TEMPLATE = BANNER + '''
_base_ = ["../../_base_/default_runtime.py"]

seed = 0
# P100 (Tufts) settings, as in linearprobe-sonata-lartpc-v5-noghost.py
batch_size = 288
batch_size_val = 132
num_worker = 22
num_worker_val = 20
mix_prob = 0.0
empty_cache = False
enable_amp = False
evaluate = True
find_unused_parameters = False

flash_backend = "xformers"   # backend needed on the Tufts P100s
amp_dtype = "float16"

enable_wandb = True
wandb_project = "pointcept_semseg"
# The probe sweep driver overrides save_path and weight per snapshot:
#   --options weight=<snapshot_iterN_imgM.pth> save_path=exp/probes/<run>/imgM
save_path = "sonata/p05/probes/default"

# PROBE BUDGET: placeholder until the WP3.5 calibration study fixes it
# (sweep epoch / base_lr via --options; then freeze for every probe).
epoch = 2
eval_epoch = 2
base_lr = 2.0e-4

# Tufts MC lists (ghost-dropped truth probing, as in the v5 probe config).
# These are the Isambard v3 MC train/val splits remapped onto Tufts source
# paths by lartpc/filelists/remap_filelists_tufts.py (same events as Isambard).
TRAIN_FILE_LIST = "/cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/isambard_pointcept/lartpc/filelists/h5list_v3_mc_only_train_tufts.txt"
VAL_FILE_LIST = "/cluster/tufts/wongjiradlabnu/twongj01/pointcept_env/isambard_pointcept/lartpc/filelists/h5list_v3_mc_only_val_tufts.txt"

grid_size = 0.25
wire_scale = 1.0 / 3456.0
coord_scale = 1036.0 * 3**0.5 / 2.0 / 5.0
scaled_grid_size = grid_size / coord_scale

max_points_spherecrop = 20480
min_points_spherecrop = 4096
biased_spherecrop_radius = 20.0

# Frozen-backbone linear probe on the SAME architecture/feature path as the
# P05 supervised ceiling. NOTE: model.backbone.head_num_prototypes must match
# the snapshot being probed — override for the prototype sweep, e.g.
#   --options model.backbone.head_num_prototypes=2048   (P05C.1)
#   --options model.backbone.head_num_prototypes=8192   (P05C.3)
model = dict(
    type="SonataSegmentor",
    num_classes=8,
    backbone_out_channels=1232,  # 48+96+192+384+512 at up_cast_level=4
    backbone=dict(
        type="Sonata-v1m1",
        backbone=dict(
            type="PT-v3m2",
            in_channels=@IN_CHANNELS@,
            order=("z", "z-trans", "hilbert", "hilbert-trans"),
            stride=(2, 2, 2, 2),
            enc_depths=(3, 3, 3, 9, 3),
            enc_channels=(48, 96, 192, 384, 512),
            enc_num_head=(3, 6, 12, 24, 32),
            enc_patch_size=(256, 256, 256, 256, 256),
            mlp_ratio=4,
            qkv_bias=True,
            qk_scale=None,
            attn_drop=0.0,
            proj_drop=0.0,
            drop_path=0.3,
            shuffle_orders=True,
            pre_norm=True,
            enable_rpe=False,
            enable_flash=True,
            flash_backend=flash_backend,
            upcast_attention=False,
            upcast_softmax=False,
            traceable=True,
            enc_mode=True,
            mask_token=True,
        ),
        head_in_channels=1088,
        head_hidden_channels=2048,
        head_embed_channels=256,
        head_num_prototypes=4096,
        num_global_view=2,
        num_local_view=6,
        up_cast_level=4,
    ),
    criteria=[
        dict(
            type="FocalLoss",
            gamma=2.0,
            alpha=0.5,
            loss_weight=1.0,
            ignore_index=-1,
            reduction="mean",
        ),
        dict(type="LovaszLoss", mode="multiclass", loss_weight=0.1, ignore_index=-1),
    ],
    freeze_backbone=True,  # linear probe: only the seg head trains
    class_priors=[0.052, 0.797, 0.009, 0.024, 0.030, 0.006, 0.077, 0.007],
)

optimizer = dict(type="AdamW", lr=base_lr, weight_decay=0.0)
scheduler = dict(
    type="OneCycleLR",
    max_lr=[base_lr],
    pct_start=0.05,
    anneal_strategy="cos",
    div_factor=1000.0,
    final_div_factor=1000.0,
)

dataset_type = "LArTPCDataset"
data_root = "data/lartpc"

# Probe-protocol data distribution (matches the P05 supervised ceiling):
# nu-anchored crops (prob_random=0.25), drop_cosmics=0.9, ghost-dropped truth.
train_transform = [
    dict(
        type="GridSample",
        grid_size=grid_size,
        hash_type="fnv",
        mode="train",
        return_grid_coord=True,
    ),
    dict(type="BiasedSphereCrop",
        anchor_points_key="nu_vertices",
        anchor_pdf_key=None,
        radius=biased_spherecrop_radius,
        point_max=max_points_spherecrop,
        point_min=min_points_spherecrop,
        prob_random=0.25,
        max_retries=100,
        fallback_to_random=True),
    dict(type="NormalizeCoord", center=[125.0, 0.0, 1036.0 / 2.0], scale=coord_scale),
    dict(
        type="LogTransform",
        min_val=0.01,
        max_val=1000.0,
        log=True,
        keys=("strength",),
    ),
@AUG_BLOCK@
    dict(type="ToTensor"),
    dict(
        type="Collect",
        keys=("coord", "grid_coord", "segment", "segment_counts"),
        feat_keys=("coord", "strength"),
    ),
]

val_transform = [
    dict(
        type="GridSample",
        grid_size=grid_size,
        hash_type="fnv",
        mode="train",
        return_grid_coord=True,
    ),
    dict(type="BiasedSphereCrop",
        anchor_points_key="nu_vertices",
        anchor_pdf_key=None,
        radius=biased_spherecrop_radius,
        point_max=max_points_spherecrop,
        point_min=min_points_spherecrop,
        prob_random=0.25,
        max_retries=100,
        fallback_to_random=True),
    dict(type="NormalizeCoord", center=[125.0, 0.0, 1036.0 / 2.0], scale=coord_scale),
    dict(
        type="LogTransform",
        min_val=0.01,
        max_val=1000.0,
        log=True,
        keys=("strength",),
    ),
    dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
    dict(type="ToTensor"),
    dict(
        type="Collect",
        keys=("coord", "grid_coord", "segment", "segment_counts"),
        feat_keys=("coord", "strength"),
    ),
]

ssnet_class_names = [
    "electron", "muon", "pion", "proton", "gamma", "michel", "delta", "led",
]

data = dict(
    num_classes=8,
    ignore_index=-1,
    names=ssnet_class_names,
    train=dict(
        type=dataset_type,
        split="train",
        data_list_file=TRAIN_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=False,
        exclude_other=True,
        transform=train_transform,
        test_mode=False,
        loop=1,
        true_points_only=True,
        data_only=False,
        filter_larmatch=False,
        drop_cosmics=True,
        drop_cosmics_prob=0.9,
    ),
    val=dict(
        type=dataset_type,
        split="val",
        data_list_file=VAL_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=False,
        exclude_other=True,
        transform=val_transform,
        test_mode=False,
        loop=1,
        true_points_only=True,
        data_only=False,
        filter_larmatch=False,
        drop_cosmics=True,
        drop_cosmics_prob=0.9,
    ),
)

hooks = [
    # Remaps sonata pretrain keys (student./teacher.*) -> backbone.*;
    # weights-only P05 snapshots load unchanged (WP2).
    dict(type="SonataCheckpointLoader"),
    dict(type="IterationTimer", warmup_iter=2),
    dict(type="InformationWriter"),
    # Mid-epoch evals log on the global-Iter axis (WP2.5).
    dict(type="SemSegEvaluator", write_cls_iou=True, eval_freq=100),
    dict(type="CheckpointSaver", save_freq=1),
]
'''

PROBE_RUNS = {
    "PROBE-p05-mc_noghost": (
        "linearprobe-sonata-p05-mc-noghost-tufts.py",
        "Linear probe for P05/v8-era snapshots (coord+strength, in_channels=6),\n"
        "run at Tufts on the frozen backbone. The v5 probe config cannot load\n"
        "these checkpoints (it assumes strength-only in_channels=3).\n"
        "Per-snapshot launch:\n"
        "  python tools/train.py --config-file configs/lartpc/p05/linearprobe-sonata-p05-mc-noghost-tufts.py \\\n"
        "      --options weight=<snapshot.pth> save_path=exp/probes/<run>/<imgM>",
        {"AUG": "detsym", "SWAP": "(0, 1)"},
    ),
}


def build_probe(run_id, filename, header, overrides):
    aug_block = DETSYM_AUG.replace("@SWAP@", overrides.get("SWAP", "(0, 1)"))
    subs = dict(
        HEADER=header,
        RUN_ID=run_id,
        IN_CHANNELS=6,
        AUG_BLOCK=aug_block,
    )
    return filename, render(PROBE_TEMPLATE, subs)


def render(template, subs):
    import re
    out = template
    for key, value in subs.items():
        out = out.replace(f"@{key}@", str(value))
    leftover = re.findall(r"@[A-Z_]+@", out)
    assert not leftover, f"unresolved placeholders: {leftover}"
    return out


ZERO_CHARGE_LINE = ('    # Geometry-only variant: replace charge features with a '
                    'constant (M3/P05A.2)\n'
                    '    dict(type="ZeroKey", keys=("strength",), value=0.0),\n')

SSL_RUNS = {
    # run_id: (filename, header, overrides)
    "P05B.1-mc_noghost-s0": (
        "pretrain-sonata-p05b1-mc-noghost-freerot.py",
        "P05B.1 — SSL on ghost-dropped MC, FREE-ROTATION augmentation policy\n"
        "(replicates v6/v7/v8 behavior: 3-axis rotations + swap-less x/y/z flips).\n"
        "Doubles as the P05C.2 prototype=4096 point and the Wave A SSL pilot.",
        {},
    ),
    "P05B.2-mc_noghost-s0": (
        "pretrain-sonata-p05b2-mc-noghost-detsym.py",
        "P05B.2 — SSL on ghost-dropped MC, DETECTOR-SYMMETRY-ONLY augmentations\n"
        "(y/z flips with u<->v charge swap; no rotations, no x-flip).",
        {"AUG": "detsym", "SWAP": "(0, 1)"},
    ),
    "P05B.4-mc_noghost-s0": (
        "pretrain-sonata-p05b4-mc-noghost-detsym-sumcharge.py",
        "P05B.4 — SSL on ghost-dropped MC, detector-symmetry augmentations with\n"
        "PLANE-SUMMED charge scalar (rotation/flip-compatible charge feature).",
        {"AUG": "detsym", "SWAP": "None", "SUMCHARGE": True, "IN_CHANNELS": 4},
    ),
    "P05C.1-mc_noghost-s0": (
        "pretrain-sonata-p05c1-mc-noghost-proto2048.py",
        "P05C.1 — prototype-count sweep: head_num_prototypes=2048\n"
        "(default free-rotation augmentations; compare with P05B.1 @ 4096).",
        {"PROTOTYPES": 2048},
    ),
    "P05C.3-mc_noghost-s0": (
        "pretrain-sonata-p05c3-mc-noghost-proto8192.py",
        "P05C.3 — prototype-count sweep: head_num_prototypes=8192.",
        {"PROTOTYPES": 8192},
    ),
    "P05C.4-mc_noghost-s0": (
        "pretrain-sonata-p05c4-mc-noghost-nuanchor.py",
        "P05C.4 — batch composition: nu-anchored crops during pretraining\n"
        "(anchor_points_key='nu_vertices', prob_random=0.25).",
        {"CROP_ANCHOR_KEY": '"nu_vertices"', "CROP_PROB_RANDOM": 0.25},
    ),
    "P05C.5-mc_noghost-s0": (
        "pretrain-sonata-p05c5-mc-noghost-dropcosmic.py",
        "P05C.5 — batch composition: high cosmic-drop fraction\n"
        "(drop_cosmics=True, prob=0.9; now instrumented with M1/M2/M5).",
        {"DROP_COSMICS": True, "DROP_COSMICS_PROB": 0.9},
    ),
    "P05C.6-mc_noghost-s0": (
        "pretrain-sonata-p05c6-mc-noghost-2xcrops.py",
        "P05C.6 — batch composition: 2x crops per batch at ~half points each\n"
        "(batch 96, point_max 10240; fixed total points per batch).",
        {"BATCH_SIZE": 96, "POINT_MAX": 10240, "MIN_POINTS": 2048},
    ),
}

SUPERVISED_RUNS = {
    "P05A.1-mc_noghost-s0": (
        "supervised-ceiling-p05a1-mc-noghost.py",
        "P05A.1 — SUPERVISED CEILING: SonataSegmentor architecture trained\n"
        "end-to-end on ghost-dropped MC, detector-symmetry augmentations,\n"
        "probe-protocol data distribution. Anchors every M6 fraction-of-ceiling.",
        {"AUG": "detsym", "SWAP": "(0, 1)"},
    ),
    "P05A.2-mc_noghost-s0": (
        "supervised-ceiling-p05a2-mc-noghost-nocharge.py",
        "P05A.2 — GEOMETRY-ONLY supervised ceiling: charge features replaced\n"
        "with a constant at train AND val. (P05A.1 - P05A.2) = total\n"
        "calorimetric information available in the features.",
        {"AUG": "detsym", "SWAP": "(0, 1)", "ZERO_CHARGE": True},
    ),
    "P05A.3-mc_noghost-s0": (
        "supervised-ceiling-p05a3-mc-noghost-freerot.py",
        "P05A.3 — supervised ceiling with PANDA-style FREE ROTATIONS\n"
        "(charge frozen): does rotation+frozen-charge hurt even supervised training?",
        {"AUG": "freerot"},
    ),
}


def build_ssl(run_id, filename, header, overrides):
    batch = overrides.get("BATCH_SIZE", BATCH_SIZE)
    aug = overrides.get("AUG", "freerot")
    if aug == "freerot":
        aug_block = FREEROT_AUG
    else:
        aug_block = DETSYM_AUG.replace("@SWAP@", overrides.get("SWAP", "(0, 1)"))
    subs = dict(
        HEADER=header,
        RUN_ID=run_id,
        BATCH_SIZE=batch,
        BASE_LR=BASE_LR,
        EPOCH=EPOCH,
        PROTOTYPES=overrides.get("PROTOTYPES", 4096),
        POINT_MAX=overrides.get("POINT_MAX", 20480),
        MIN_POINTS=overrides.get("MIN_POINTS", 4096),
        IN_CHANNELS=overrides.get("IN_CHANNELS", 6),
        SNAPSHOT_ITERS=snapshot_iters(batch),
        GLOBAL_AUG=aug_block,
        LOCAL_AUG=aug_block,
        STRENGTH_REDUCE=CHANNEL_REDUCE_LINE if overrides.get("SUMCHARGE") else "",
        CROP_ANCHOR_KEY=overrides.get("CROP_ANCHOR_KEY", "None"),
        CROP_PROB_RANDOM=overrides.get("CROP_PROB_RANDOM", 1.0),
        DROP_COSMICS=overrides.get("DROP_COSMICS", False),
        DROP_COSMICS_PROB=overrides.get("DROP_COSMICS_PROB", 0.5),
        TRAIN_LIST=MC_TRAIN,
        VAL_LIST=MC_VAL,
    )
    return filename, render(SSL_TEMPLATE, subs)


def build_supervised(run_id, filename, header, overrides):
    aug = overrides.get("AUG", "detsym")
    if aug == "freerot":
        aug_block = FREEROT_AUG
    else:
        aug_block = DETSYM_AUG.replace("@SWAP@", overrides.get("SWAP", "(0, 1)"))
    # Indentation inside the enclosing [...] is syntactically free, so the
    # aug block is embedded verbatim as list items.
    aug_lines = aug_block
    subs = dict(
        HEADER=header,
        RUN_ID=run_id,
        BATCH_SIZE=BATCH_SIZE,
        BASE_LR=BASE_LR,
        EPOCH=EPOCH,
        IN_CHANNELS=6,
        AUG_BLOCK=aug_lines,
        ZERO_CHARGE=ZERO_CHARGE_LINE if overrides.get("ZERO_CHARGE") else "",
        TRAIN_LIST=MC_TRAIN,
        VAL_LIST=MC_VAL,
    )
    return filename, render(SUPERVISED_TEMPLATE, subs)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    written = []
    for run_id, (filename, header, overrides) in SSL_RUNS.items():
        fn, text = build_ssl(run_id, filename, header, overrides)
        with open(os.path.join(OUT_DIR, fn), "w") as f:
            f.write(text)
        written.append(fn)
    for run_id, (filename, header, overrides) in SUPERVISED_RUNS.items():
        fn, text = build_supervised(run_id, filename, header, overrides)
        with open(os.path.join(OUT_DIR, fn), "w") as f:
            f.write(text)
        written.append(fn)
    for run_id, (filename, header, overrides) in PROBE_RUNS.items():
        fn, text = build_probe(run_id, filename, header, overrides)
        with open(os.path.join(OUT_DIR, fn), "w") as f:
            f.write(text)
        written.append(fn)
    print(f"wrote {len(written)} configs to {OUT_DIR}:")
    for fn in written:
        print(f"  {fn}")


if __name__ == "__main__":
    main()
