"""
AUTO-GENERATED by lartpc/pretraining_studies/gen_p05_configs.py — DO NOT HAND-EDIT.
Regenerate with:  python3 lartpc/pretraining_studies/gen_p05_configs.py

P05B.6 — as P05B.5 (asinh scaling, exact value-space jitter) but
sigma=clip=0.05: ONE delta (jitter magnitude) against P05B.5 —
does the charge-jitter strength itself matter under asinh?
PI decision 2026-07-16. (The 4th factorial cell — log transform with
exact 0.05 jitter — is intentionally not generated; handoff §2.3.)
Probe snapshots with linearprobe-sonata-p05-mc-noghost-asinh-tufts.py.
"""

_base_ = ["../../_base_/default_runtime.py"]

# ---- Phase 0.5 locked budget (do not vary within P05 comparisons) ----
seed = 0
batch_size = 48
batch_size_val = 8
num_worker = 24
mix_prob = 0
clip_grad = 1.0
empty_cache = True
enable_amp = False
evaluate = False  # SSL runs are probed offline at Tufts (implementation plan WP3)
find_unused_parameters = False

skip_dataloader_on_resume = True
resume_seed_strategy = "per_resume"

flash_backend = "flash_attn"
amp_dtype = "bfloat16"

enable_wandb = True
wandb_project = "pointcept_p05_pretrain"
save_path = "sonata/p05/P05B.6-mc_noghost-s0"

TRAIN_FILE_LIST = "/projects/u6jo/work/pointcept/lartpc/filelists/h5list_v3_mc_only_train.txt"
VAL_FILE_LIST = "/projects/u6jo/work/pointcept/lartpc/filelists/h5list_v3_mc_only_val.txt"

max_points_per_view = 20480
max_points_spherecrop = 20480
min_points_spherecrop = 4096
biased_spherecrop_radius = 20.0

# scheduler settings
epoch = 12
eval_epoch = 12
base_lr = 0.0002
lr_final_div_factor = 1000.0
lr_pct_start = 0.06
lr_decay = 0.9  # layer-wise lr decay
base_wd = 0.04
final_wd = 0.2

# LArTPC scale parameters
grid_size = 0.25  # cm
wire_scale = 1.0 / 3456.0
coord_scale = 1036.0 * 3**0.5 / 2.0 / 5.0
scaled_grid_size = grid_size / coord_scale

# Weights-only snapshots for probe curves (metric vs images seen); the
# snapshot/ directory is rsync'd to Tufts as points accumulate (WP2/WP3).
snapshot_at_iters = [500, 1000, 2000, 4000, 8000, 16000, 32000, 48000, 64000, 80000, 96000]

# model settings
model = dict(
    type="Sonata-v1m1",
    backbone=dict(
        type="PT-v3m2",  # Must use v3m2 for SONATA (supports mask_token)
        in_channels=6,
        order=("z", "z-trans", "hilbert", "hilbert-trans"),
        stride=(2, 2, 2, 2),
        enc_depths=(3, 3, 3, 9, 3),
        enc_channels=(48, 96, 192, 384, 512),
        enc_num_head=(3, 6, 12, 24, 32),
        enc_patch_size=(256, 256, 256, 256, 256),
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        attn_drop=0.0,
        proj_drop=0.0,
        drop_path=0.3,
        shuffle_orders=True,
        pre_norm=True,
        enable_rpe=False,
        enable_flash=True,
        flash_backend=flash_backend,
        upcast_attention=False,
        upcast_softmax=False,
        traceable=True,
        enc_mode=True,
        mask_token=True,
    ),
    teacher_custom=dict(
        attn_drop=0.0,
        proj_drop=0.0,
        drop_path=0.0,
    ),
    head_in_channels=1088,  # up_cast_level=2: 192 + 384 + 512
    head_hidden_channels=2048,
    head_embed_channels=256,
    head_num_prototypes=4096,
    num_global_view=2,
    num_local_view=6,
    mask_size_start=2.0 / coord_scale,
    mask_size_base=15.0 / coord_scale,
    mask_size_warmup_ratio=0.06,
    mask_ratio_start=0.2,
    mask_ratio_base=0.7,
    mask_ratio_warmup_ratio=0.06,
    mask_jitter=0.125 / coord_scale,
    teacher_temp_start=0.04,
    teacher_temp_base=0.07,
    teacher_temp_warmup_ratio=0.06,
    student_temp=0.1,
    mask_loss_weight=2 / 8,
    roll_mask_loss_weight=2 / 8,
    unmask_loss_weight=4 / 8,
    momentum_base=0.994,
    momentum_final=1.0,
    match_max_k=8,
    match_max_r=16.0 * grid_size / coord_scale,
    up_cast_level=2,
)

# Layer-wise learning rate decay
enc_depths = model["backbone"]["enc_depths"]
param_dicts = [
    dict(
        keyword=f"enc{e}.block{b}.",
        lr=base_lr * lr_decay ** (sum(enc_depths) - sum(enc_depths[:e]) - b - 1),
    )
    for e in range(len(enc_depths))
    for b in range(enc_depths[e])
]
del enc_depths

optimizer = dict(type="AdamW", lr=base_lr, weight_decay=base_wd)
scheduler = dict(
    type="OneCycleLR",
    max_lr=[base_lr] + [g["lr"] for g in param_dicts],
    pct_start=lr_pct_start,
    anneal_strategy="cos",
    div_factor=100.0,
    final_div_factor=lr_final_div_factor,
)

# dataset settings
dataset_type = "LArTPCDataset"
data_root = "data/lartpc"

transform = [
    dict(
        type="GridSample",
        grid_size=grid_size,
        hash_type="fnv",
        mode="train",
        return_grid_coord=True,
    ),
    dict(type="BiasedSphereCrop",
        anchor_points_key=None,
        anchor_pdf_key=None,
        radius=biased_spherecrop_radius,
        point_max=max_points_spherecrop,
        point_min=min_points_spherecrop,
        prob_random=1.0,
        max_retries=100,
        fallback_to_random=True),
    dict(type="NormalizeCoord", center=[125.0, 0.0, 1036.0 / 2.0], scale=coord_scale),
    # P05F verdict (input_dist_study): asinh(scale=50) over [0, 1000] keeps the
    # mu/pi/p dE/dx separation the log scaling squashes; xmax matches the
    # loader clip, so the loader is untouched.
    dict(
        type="LogTransform",
        mode="asinh",
        asinh_scale=50.0,
        max_val=1000.0,
        keys=("strength",),
    ),
    dict(type="Copy", keys_dict={"coord": "origin_coord"}),
    dict(
        type="MultiViewGenerator",
        # "segment" rides along so the M5 BatchCompositionLogger can measure
        # per-batch truth-class fractions (labels are NOT used by the loss).
        view_keys=("coord", "origin_coord", "strength", "segment"),
        global_view_num=2,
        global_view_scale=(0.4, 1.0),
        local_view_num=6,
        local_view_scale=(0.1, 0.4),
        global_shared_transform=[
            dict(
                # exact value-space jitter (handoff §2.2/§2.3): stays in [-1,1]
                type="MultiplicativeRandomJitter",
                sigma=0.05,
                clip=0.05,
                keys=("strength"),
                p=0.8,
                value_space="asinh",
                asinh_scale=50.0,
                max_val=1000.0,
            ),
        ],
        global_transform=[
            dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
            # Free 3-axis rotations + swap-less x/y/z flips: replicates the
            # v6/v7/v8 policy exactly (charge-INconsistent by design).
            dict(type="RandomRotate", angle=[-1, 1], axis="z", center=[0, 0, 0], p=0.8),
            dict(type="RandomRotate", angle=[-1, 1], axis="x", center=[0, 0, 0], p=0.8),
            dict(type="RandomRotate", angle=[-1, 1], axis="y", center=[0, 0, 0], p=0.8),
            dict(type="RandomFlip", p=0.5, axes=("x", "y", "z")),
            dict(
                type="RandomJitter",
                sigma=scaled_grid_size / 4,
                clip=scaled_grid_size,
                keys=("coord",),
            ),
        ],
        local_transform=[
            dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
            # Free 3-axis rotations + swap-less x/y/z flips: replicates the
            # v6/v7/v8 policy exactly (charge-INconsistent by design).
            dict(type="RandomRotate", angle=[-1, 1], axis="z", center=[0, 0, 0], p=0.8),
            dict(type="RandomRotate", angle=[-1, 1], axis="x", center=[0, 0, 0], p=0.8),
            dict(type="RandomRotate", angle=[-1, 1], axis="y", center=[0, 0, 0], p=0.8),
            dict(type="RandomFlip", p=0.5, axes=("x", "y", "z")),
            dict(
                type="RandomJitter",
                sigma=scaled_grid_size / 4,
                clip=scaled_grid_size,
                keys=("coord",),
            ),
        ],
        max_size=max_points_per_view,
    ),
    dict(type="ToTensor"),
    dict(type="Update", keys_dict={"grid_size": scaled_grid_size}),
    dict(
        type="Collect",
        keys=(
            "global_origin_coord",
            "global_coord",
            "global_offset",
            "global_segment",
            "local_origin_coord",
            "local_coord",
            "local_offset",
            "grid_size",
            "name",
        ),
        offset_keys_dict=dict(),
        global_feat_keys=("global_coord", "global_strength",),
        local_feat_keys=("local_coord", "local_strength",),
    ),
]

# Single-view validation pipeline (kept consistent with the feature pipeline;
# only used if an in-loop evaluator is enabled).
val_transform = [
    dict(
        type="GridSample",
        grid_size=grid_size,
        hash_type="fnv",
        mode="train",
        return_grid_coord=True,
    ),
    dict(type="BiasedSphereCrop",
        anchor_points_key=None,
        anchor_pdf_key=None,
        radius=biased_spherecrop_radius,
        point_max=max_points_spherecrop,
        point_min=min_points_spherecrop,
        prob_random=1.0,
        max_retries=100,
        fallback_to_random=True),
    dict(type="NormalizeCoord", center=[125.0, 0.0, 1036.0 / 2.0], scale=coord_scale),
    # P05F verdict (input_dist_study): asinh(scale=50) over [0, 1000] keeps the
    # mu/pi/p dE/dx separation the log scaling squashes; xmax matches the
    # loader clip, so the loader is untouched.
    dict(
        type="LogTransform",
        mode="asinh",
        asinh_scale=50.0,
        max_val=1000.0,
        keys=("strength",),
    ),
    dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
    dict(type="ToTensor"),
    dict(
        type="Collect",
        keys=("coord", "grid_coord", "segment"),
        feat_keys=("coord", "strength"),
    ),
]

ssnet_class_names = [
    "electron", "muon", "pion", "proton", "gamma", "michel", "delta", "led",
]

data = dict(
    num_classes=8,
    ignore_index=-1,
    names=ssnet_class_names,
    train=dict(
        type=dataset_type,
        split="train",
        data_list_file=TRAIN_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=False,
        exclude_other=False,
        transform=transform,
        test_mode=False,
        loop=1,
        # ---- Phase 0.5: ghost-dropped MC with truth loaded ----
        true_points_only=True,
        data_only=False,
        filter_larmatch=False,
        drop_cosmics=False,
        drop_cosmics_prob=0.5,
    ),
    val=dict(
        type=dataset_type,
        split="val",
        data_list_file=VAL_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=False,
        exclude_other=False,
        transform=val_transform,
        test_mode=False,
        loop=1,
        true_points_only=True,
        data_only=False,
        filter_larmatch=False,
    ),
)

hooks = [
    dict(type="CheckpointLoader", extend_scheduler=False),
    dict(type="ModelHook"),
    dict(type="WeightDecaySchedular", base_value=base_wd, final_value=final_wd,
         extend_scheduler=False, original_total_steps=None),
    dict(type="IterationTimer", warmup_iter=2),
    dict(type="InformationWriter"),
    dict(type="CheckpointSaver", save_freq=1),
    # Resumable mid-epoch saves + retained weights-only snapshots (WP2).
    dict(type="IterCheckpointSaver", save_iter_freq=50, keep_history=False,
         snapshot_at_iters=snapshot_at_iters),
    dict(type="SignalCheckpointHook", check_every_n_iter=30),
    # M5: per-batch truth-class composition (implementation plan WP5).
    dict(type="BatchCompositionLogger", log_frequency=50,
         segment_key="global_segment"),
    dict(
        type="GradScalerMonitor",
        log_frequency=10,
        prefix="grad_scaler",
        warn_on_overflow=True,
        warn_on_low_scale=1.0,
    ),
    dict(
        type="AdamStateMonitor",
        log_frequency=100,
        prefix="adam_state",
        track_layers=True,
        track_histograms=False,
        histogram_frequency=500,
    ),
    dict(
        type="PrototypeUsageLogger",
        log_frequency=10,
        prefix="prototypes",
    ),
    dict(
        type="FeatureStdMonitor",
        log_frequency=10,
        prefix="feature_std",
        monitor_student=True,
        monitor_teacher=True,
        track_channels=False,
    ),
]
