"""
AUTO-GENERATED by lartpc/pretraining_studies/gen_p05_configs.py — DO NOT HAND-EDIT.
Regenerate with:  python3 lartpc/pretraining_studies/gen_p05_configs.py

P05A.2 — GEOMETRY-ONLY supervised ceiling: charge features replaced
with a constant at train AND val. (P05A.1 - P05A.2) = total
calorimetric information available in the features.
"""

_base_ = ["../../_base_/default_runtime.py"]

seed = 0
batch_size = 48
batch_size_val = 48
num_worker = 24
mix_prob = 0.0
clip_grad = 1.0
empty_cache = False
enable_amp = False
evaluate = True
# The wrapped Sonata module's student branch is unused when training the
# (teacher) encoder end-to-end through SonataSegmentor.
find_unused_parameters = True

skip_dataloader_on_resume = True
resume_seed_strategy = "per_resume"

flash_backend = "flash_attn"
amp_dtype = "bfloat16"

enable_wandb = True
wandb_project = "pointcept"
save_path = "sonata/p05/P05A.2-mc_noghost-s0"

TRAIN_FILE_LIST = "/projects/u6jo/work/pointcept/lartpc/filelists/h5list_v3_mc_only_train.txt"
VAL_FILE_LIST = "/projects/u6jo/work/pointcept/lartpc/filelists/h5list_v3_mc_only_val.txt"

grid_size = 0.25
wire_scale = 1.0 / 3456.0
coord_scale = 1036.0 * 3**0.5 / 2.0 / 5.0
scaled_grid_size = grid_size / coord_scale

max_points_spherecrop = 20480
min_points_spherecrop = 4096
biased_spherecrop_radius = 20.0

epoch = 12
eval_epoch = 12
base_lr = 0.0002

# =============================================================================
# Supervised ceiling: SAME architecture and feature path as the SSL probes
# (SonataSegmentor + PT-v3m2 encoder + up_cast_level=4 + linear head), trained
# END-TO-END from random init. This makes the M6 fraction-of-ceiling
# comparison probe-vs-ceiling apples-to-apples.
# =============================================================================
model = dict(
    type="SonataSegmentor",
    num_classes=8,
    backbone_out_channels=1232,  # 48+96+192+384+512 at up_cast_level=4
    backbone=dict(
        type="Sonata-v1m1",
        backbone=dict(
            type="PT-v3m2",
            in_channels=6,
            order=("z", "z-trans", "hilbert", "hilbert-trans"),
            stride=(2, 2, 2, 2),
            enc_depths=(3, 3, 3, 9, 3),
            enc_channels=(48, 96, 192, 384, 512),
            enc_num_head=(3, 6, 12, 24, 32),
            enc_patch_size=(256, 256, 256, 256, 256),
            mlp_ratio=4,
            qkv_bias=True,
            qk_scale=None,
            attn_drop=0.0,
            proj_drop=0.0,
            drop_path=0.3,
            shuffle_orders=True,
            pre_norm=True,
            enable_rpe=False,
            enable_flash=True,
            flash_backend=flash_backend,
            upcast_attention=False,
            upcast_softmax=False,
            traceable=True,
            enc_mode=True,
            mask_token=True,
        ),
        head_in_channels=1088,
        head_hidden_channels=2048,
        head_embed_channels=256,
        head_num_prototypes=4096,
        num_global_view=2,
        num_local_view=6,
        up_cast_level=4,
    ),
    criteria=[
        dict(
            type="FocalLoss",
            gamma=2.0,
            alpha=0.5,
            loss_weight=1.0,
            ignore_index=-1,
            reduction="mean",
        ),
        dict(type="LovaszLoss", mode="multiclass", loss_weight=0.1, ignore_index=-1),
    ],
    freeze_backbone=False,  # supervised: train the encoder end-to-end
    class_priors=[0.052, 0.797, 0.009, 0.024, 0.030, 0.006, 0.077, 0.007],
)

optimizer = dict(type="AdamW", lr=base_lr, weight_decay=0.04)
scheduler = dict(
    type="OneCycleLR",
    max_lr=[base_lr],
    pct_start=0.06,
    anneal_strategy="cos",
    div_factor=100.0,
    final_div_factor=1000.0,
)

dataset_type = "LArTPCDataset"
data_root = "data/lartpc"

# Data distribution mirrors the probe protocol (BASE_LINPROBE): nu-anchored
# crops (prob_random=0.25) and drop_cosmics=0.9, so ceiling and probe numbers
# are measured on the same event distribution.
train_transform = [
    dict(
        type="GridSample",
        grid_size=grid_size,
        hash_type="fnv",
        mode="train",
        return_grid_coord=True,
    ),
    dict(type="BiasedSphereCrop",
        anchor_points_key="nu_vertices",
        anchor_pdf_key=None,
        radius=biased_spherecrop_radius,
        point_max=max_points_spherecrop,
        point_min=min_points_spherecrop,
        prob_random=0.25,
        max_retries=100,
        fallback_to_random=True),
    dict(type="NormalizeCoord", center=[125.0, 0.0, 1036.0 / 2.0], scale=coord_scale),
    dict(
        type="LogTransform",
        min_val=0.01,
        max_val=1000.0,
        log=True,
        keys=("strength",),
    ),
    # Geometry-only variant: replace charge features with a constant (M3/P05A.2)
    dict(type="ZeroKey", keys=("strength",), value=0.0),
            dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
            # Detector symmetries only: y-flip and z-flip with u<->v
            # charge-column swap (reviewed correct — implementation plan §1.5).
            # No rotations (tomographic charge consistency), no x-flip
            # (drift-direction asymmetry: diffusion, attenuation).
            dict(type="RandomFlipAxis", p=0.5, axis="y", center="mean",
                 coord_scale=1.0, swap_strength_columns=(0, 1),
                 wire_projections=None),
            dict(type="RandomFlipAxis", p=0.5, axis="z", center="mean",
                 coord_scale=1.0, swap_strength_columns=(0, 1),
                 wire_projections=None),
            dict(
                type="RandomJitter",
                sigma=scaled_grid_size / 4,
                clip=scaled_grid_size,
                keys=("coord",),
            ),
    dict(type="ToTensor"),
    dict(
        type="Collect",
        keys=("coord", "grid_coord", "segment", "segment_counts"),
        feat_keys=("coord", "strength"),
    ),
]

val_transform = [
    dict(
        type="GridSample",
        grid_size=grid_size,
        hash_type="fnv",
        mode="train",
        return_grid_coord=True,
    ),
    dict(type="BiasedSphereCrop",
        anchor_points_key="nu_vertices",
        anchor_pdf_key=None,
        radius=biased_spherecrop_radius,
        point_max=max_points_spherecrop,
        point_min=min_points_spherecrop,
        prob_random=0.25,
        max_retries=100,
        fallback_to_random=True),
    dict(type="NormalizeCoord", center=[125.0, 0.0, 1036.0 / 2.0], scale=coord_scale),
    dict(
        type="LogTransform",
        min_val=0.01,
        max_val=1000.0,
        log=True,
        keys=("strength",),
    ),
    # Geometry-only variant: replace charge features with a constant (M3/P05A.2)
    dict(type="ZeroKey", keys=("strength",), value=0.0),
    dict(type="CenterShift", apply_z=False, axes=("x", "y", "z")),
    dict(type="ToTensor"),
    dict(
        type="Collect",
        keys=("coord", "grid_coord", "segment", "segment_counts"),
        feat_keys=("coord", "strength"),
    ),
]

ssnet_class_names = [
    "electron", "muon", "pion", "proton", "gamma", "michel", "delta", "led",
]

data = dict(
    num_classes=8,
    ignore_index=-1,
    names=ssnet_class_names,
    train=dict(
        type=dataset_type,
        split="train",
        data_list_file=TRAIN_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=False,
        exclude_other=True,
        transform=train_transform,
        test_mode=False,
        loop=1,
        true_points_only=True,
        data_only=False,
        filter_larmatch=False,
        drop_cosmics=True,
        drop_cosmics_prob=0.9,
    ),
    val=dict(
        type=dataset_type,
        split="val",
        data_list_file=VAL_FILE_LIST,
        use_reco_coords=True,
        use_edep_as_strength=True,
        label_mode="ssnet",
        coord_scale=1.0,
        include_ghosts=False,
        exclude_other=True,
        transform=val_transform,
        test_mode=False,
        loop=1,
        true_points_only=True,
        data_only=False,
        filter_larmatch=False,
        drop_cosmics=True,
        drop_cosmics_prob=0.9,
    ),
)

hooks = [
    dict(type="CheckpointLoader"),
    dict(type="IterationTimer", warmup_iter=2),
    dict(type="InformationWriter"),
    # In-loop val on Isambard (implementation plan §1.4): mid-epoch evals log
    # on the global-Iter axis (WP2.5 fix in SemSegEvaluator).
    dict(type="SemSegEvaluator", write_cls_iou=True, eval_freq=1000),
    dict(type="CheckpointSaver", save_freq=1),
    dict(type="IterCheckpointSaver", save_iter_freq=500, keep_history=False),
    dict(type="SignalCheckpointHook", check_every_n_iter=30),
    dict(type="BatchCompositionLogger", log_frequency=50, segment_key="segment"),
]
